Update Spanish language file.
thesupersonic16/HedgeModManager pull request #214
Opened 2021-04-29 17:03 UTC by ricky-daniel13

Added and translated missing strings.

2021-04-29 17:34 UTC, TProaa requested changes
I would suggest fixing the capitalization in 29 and in 138 so it doesn't look that off. And also changing the word "de" to "del" in both instances. Aside from that, solid translation.

2021-04-29 17:34 UTC, TProaa commented on HedgeModManager/Languages/es-MX.xaml
> +    <system:String x:Key="MainUIMLDownloadFail">Descarga de Cargador de mods Fallida</system:String>
```suggestion
    <system:String x:Key="MainUIMLDownloadFail">Descarga del cargador de mods fallida</system:String>
```

2021-04-29 17:34 UTC, TProaa commented on HedgeModManager/Languages/es-MX.xaml
> +    <system:String x:Key="ModDownloaderFailed">Descarga de Mod fallida</system:String>
```suggestion
    <system:String x:Key="ModDownloaderFailed">Descarga del mod fallida</system:String>
```

2021-04-30 15:16 UTC, merged

2021-04-30 15:16 UTC, thesupersonic16 commented
LGTM