[Translate] Update Chinese (Simplified) Strings
thesupersonic16/HedgeModManager pull request #555
Opened 2023-01-02 13:23 UTC by AlanYe-Dev

2023-01-02 16:09 UTC, HyperBE32 requested changes

2023-01-02 16:09 UTC, HyperBE32 commented on HedgeModManager/Languages/zh-CN.xaml
> +    <system:String x:Key="DiffUIModified" >重命名: </system:String>
Please add `{0}` to the end of all of these strings except for `DiffUITitle`, this is required to display the name of the code that has changed.

2023-01-03 00:53 UTC, AlanYe-Dev commented
Updated

2023-01-04 01:30 UTC, HyperBE32 approved these changes

2023-01-05 07:15 UTC, merged