[Sonic Frontiers] Added a description to every code that didn't already have one
thesupersonic16/HedgeModManager pull request #701
Opened 2023-08-27 01:53 UTC by jubbalub

2023-08-28 06:23 UTC, HyperBE32 requested changes
A lot of these descriptions don't really need to exist when the name of the code is sufficient enough.

All rejected descriptions are marked as redundant, please remove them.

2023-08-28 06:23 UTC, hyperbx commented on HedgeModManager/Resources/Codesv2/SonicFrontiers.hmm
> +Patch "Restore Unused Spin Charge Camera Shake" in "Camera" by "Hyper" does "Restores the unused camera shake effect when charging a Spin Dash."
Remove "effect" from the description.

2023-08-28 06:23 UTC, HyperBE32 commented on HedgeModManager/Resources/Codesv2/SonicFrontiers.hmm
> +Patch "Infinite Quick Cyloop Gauge" in "Cheats" by "NM" does "Grants unlimited Quick Cyloop gauge."
Redundant.

2023-08-28 06:23 UTC, HyperBE32 commented on HedgeModManager/Resources/Codesv2/SonicFrontiers.hmm
> +Patch "Infinite Skill Points" in "Cheats" by "Hyper" does "Grants unlimited Skill Points."
Redundant.

2023-08-28 06:23 UTC, hyperbx commented on HedgeModManager/Resources/Codesv2/SonicFrontiers.hmm
> +Patch "Infinite Boost Gauge" in "Cheats" by "Hyper" does "Grants unlimited boost gauge."
Redundant.

2023-08-28 06:23 UTC, HyperBE32 commented on HedgeModManager/Resources/Codesv2/SonicFrontiers.hmm
> +Patch "Hide Titan Health Gauge" in "UI" by "Hyper" does "Disables the Titan health bar gauge."
Redundant.

2023-08-28 06:23 UTC, HyperBE32 commented on HedgeModManager/Resources/Codesv2/SonicFrontiers.hmm
> +Patch "Hide Power Boost Effects" in "Graphics" by "NM & Hyper" does "Disables the Power Boost's unique visual effects."
Redundant.

2023-08-28 06:23 UTC, HyperBE32 commented on HedgeModManager/Resources/Codesv2/SonicFrontiers.hmm
> +Patch "Hide Oxygen Gauge" in "UI" by "Hyper" does "Disabled the oxygen gauge UI element."
Redundant.

2023-08-28 06:23 UTC, HyperBE32 commented on HedgeModManager/Resources/Codesv2/SonicFrontiers.hmm
> +Code "Show Frame Rate on Title Bar" in "System" by "Hyper & Sajid" does "Displays the game's current frame rate in the title bar."
Change to "Displays the current frame rate and frame time on the title bar."

2023-08-28 06:23 UTC, HyperBE32 commented on HedgeModManager/Resources/Codesv2/SonicFrontiers.hmm
> +Patch "Hide Target Reticle" in "UI" by "Hyper" does "Disables the Homing Attack reticle displayed when in range, as well as the lock-on triangle indicator."
Change to "Hides the attack reticle and lock-on indicator."

2023-08-28 06:23 UTC, HyperBE32 commented on HedgeModManager/Resources/Codesv2/SonicFrontiers.hmm
> +Patch "Hide Cyber Space Timer" in "UI" by "Hyper" does "Disables the timer UI element in Cyber Space."
Redundant.

2023-08-28 06:23 UTC, HyperBE32 commented on HedgeModManager/Resources/Codesv2/SonicFrontiers.hmm
> +Patch "Hide Boost Gauge" in "UI" by "Hyper" does "Disables the Boost gauge UI element."
Redundant.

2023-08-28 06:23 UTC, HyperBE32 commented on HedgeModManager/Resources/Codesv2/SonicFrontiers.hmm
> +Patch "Hide Air Trick Hint Effects" in "Graphics" by "Hyper" does "Hides the particles that signify dash rings, jump boards and springs are trickable."
Redundant.

2023-08-28 06:23 UTC, HyperBE32 commented on HedgeModManager/Resources/Codesv2/SonicFrontiers.hmm
> +Patch "Force Xbox Series S/X Controller UI" in "UI" by "Hyper" does "Forces the Xbox Series S/X controller UI to be used."
Change "S/X" to "X|S", as that's how it is branded. The description is redundant.

2023-08-28 06:23 UTC, HyperBE32 commented on HedgeModManager/Resources/Codesv2/SonicFrontiers.hmm
> +Patch "Force Xbox One Controller UI" in "UI" by "Hyper" does "Forces the Xbox One controller UI to be used."
Redundant.

2023-08-28 06:23 UTC, HyperBE32 commented on HedgeModManager/Resources/Codesv2/SonicFrontiers.hmm
> +Patch "Force Switch Controller UI" in "UI" by "Hyper" does "Forces the Nintendo Switch controller UI to be used."
Redundant.

2023-08-28 06:23 UTC, HyperBE32 commented on HedgeModManager/Resources/Codesv2/SonicFrontiers.hmm
> +Patch "Force PlayStation 5 Controller UI" in "UI" by "Hyper" does "Forces the PlayStation 5 controller UI to be used."
Redundant.

2023-08-28 06:23 UTC, HyperBE32 commented on HedgeModManager/Resources/Codesv2/SonicFrontiers.hmm
> +Patch "Force PlayStation 4 Controller UI" in "UI" by "Hyper" does "Forces the PlayStation 4 controller UI to be used."
Redundant.

2023-08-28 06:23 UTC, HyperBE32 commented on HedgeModManager/Resources/Codesv2/SonicFrontiers.hmm
> +Patch "Disable Vignette" in "Graphics" by "Hyper" does "Disables the vignette around the edges of the camera."
Change to "Disables the edge darkening effect around the screen." Using the term "vignette" again is redundant and doesn't really explain what it is.

2023-08-28 06:23 UTC, HyperBE32 commented on HedgeModManager/Resources/Codesv2/SonicFrontiers.hmm
> +Patch "Disable Umbrella Camera Lock-On" in "Camera" by "Hyper" does "Disables the lock-on camera when the Umbrella enemy jumps into the sky."
What's the point in removing this? It makes it more clear which enemy is being referred to, seeing as you have to dig through concept art for the enemy names.

2023-08-28 06:23 UTC, HyperBE32 commented on HedgeModManager/Resources/Codesv2/SonicFrontiers.hmm
> +Patch "Disable Water Audio Filter" in "Audio" by "Hyper" does "Disables the audio filter used while underwater."
Redundant.

2023-08-28 06:23 UTC, HyperBE32 commented on HedgeModManager/Resources/Codesv2/SonicFrontiers.hmm
> +Patch "Disable Subsurface Scattering" in "Graphics" by "Hyper" does "Disables subsurface scattering."
Redundant.

2023-08-28 06:23 UTC, HyperBE32 commented on HedgeModManager/Resources/Codesv2/SonicFrontiers.hmm
> +Patch "Disable Starfall Cutscene" in "Gameplay" by "Hyper" does "Disables the cutscene that occurs before a Starfall."
Redundant.

2023-08-28 06:23 UTC, HyperBE32 commented on HedgeModManager/Resources/Codesv2/SonicFrontiers.hmm
> +Patch "Disable Spin Slash on Drop Dash" in "Gameplay" by "Hyper" does "Disables performing the Spin Slash when getting close to an enemy while drop dashing."
Change to "Disables performing a Spin Slash after a Drop Dash whilst in combat."

2023-08-28 06:23 UTC, HyperBE32 commented on HedgeModManager/Resources/Codesv2/SonicFrontiers.hmm
> +Patch "Disable Shadows" in "Graphics" by "Luig & Hyper" does "Disables shadows."
Redundant.

2023-08-28 06:23 UTC, HyperBE32 commented on HedgeModManager/Resources/Codesv2/SonicFrontiers.hmm
> +Patch "Disable Ring Loss" in "Cheats" by "M&M" does "Sonic no longer loses rings when taking damage."
Change to "Disables losing rings after taking damage."

2023-08-28 06:23 UTC, HyperBE32 commented on HedgeModManager/Resources/Codesv2/SonicFrontiers.hmm
> +Patch "Disable Power Boost Audio" in "Audio" by "Hyper" does "Disables the Power Boost's unique sound effects."
Redundant.

2023-08-28 06:23 UTC, HyperBE32 commented on HedgeModManager/Resources/Codesv2/SonicFrontiers.hmm
> +Patch "Disable Power Boost" in "Gameplay" by "Hyper" does "Disables the Power Boost."
Redundant.

2023-08-28 06:23 UTC, HyperBE32 commented on HedgeModManager/Resources/Codesv2/SonicFrontiers.hmm
> +Patch "Disable Photo Mode Zoom Limit" in "Camera" by "Hyper" does "Disables the zoom limit for Photo Mode."
Redundant.

2023-08-28 06:23 UTC, HyperBE32 commented on HedgeModManager/Resources/Codesv2/SonicFrontiers.hmm
> +Patch "Disable Photo Mode Tilt Limit" in "Camera" by "Hyper" does "Disables the tilt limit for Photo Mode."
Redundant.

2023-08-28 06:23 UTC, HyperBE32 commented on HedgeModManager/Resources/Codesv2/SonicFrontiers.hmm
> +Patch "Disable Photo Mode Distance Limit" in "Camera" by "Hyper" does "Disables the distance limit for Photo Mode."
Redundant.

2023-08-28 06:23 UTC, HyperBE32 commented on HedgeModManager/Resources/Codesv2/SonicFrontiers.hmm
> +Patch "Disable Photo Mode Camera Collision" in "Camera" by "Hyper" does "Disables camera collision in Photo Mode, allowing the camera to pass through terrain."
Redundant.

2023-08-28 06:23 UTC, HyperBE32 commented on HedgeModManager/Resources/Codesv2/SonicFrontiers.hmm
> +Patch "Disable Loop Kick on Slide" in "Gameplay" by "Hyper" does "Disables performing Loop Kick upon getting close to an enemy while sliding."
Change to "Disables performing a Loop Kick when sliding near an enemy."

2023-08-28 06:23 UTC, HyperBE32 commented on HedgeModManager/Resources/Codesv2/SonicFrontiers.hmm
> +Code "Disable Lava Instant Death" in "Gameplay" by "Hyper" does "Disables Sonic instantly dying to lava, and instead makes him lose rings and launch into the air."
Use the original description and change "drowning" to "dying".

2023-08-28 06:23 UTC, HyperBE32 commented on HedgeModManager/Resources/Codesv2/SonicFrontiers.hmm
> +Patch "Disable Hit Stop" in "Gameplay" by "Hyper" does "Disables the slow-motion effect after performing certain attacks."
Remove the hyphen in "slow motion".

2023-08-28 06:23 UTC, HyperBE32 commented on HedgeModManager/Resources/Codesv2/SonicFrontiers.hmm
> +Patch "Disable Grass" in "Graphics" by "Hyper" does "Disables grass foliage."
Redundant.

2023-08-28 06:23 UTC, HyperBE32 commented on HedgeModManager/Resources/Codesv2/SonicFrontiers.hmm
> +Patch "Disable Drop Dash Camera Delay" in "Camera" by "Hyper" does "Disables the camera delay upon performing a Drop Dash."
Redundant.

2023-08-28 06:23 UTC, HyperBE32 commented on HedgeModManager/Resources/Codesv2/SonicFrontiers.hmm
> +Patch "Disable Drop Dash" in "Gameplay" by "Hyper" does "Disables the Drop Dash."
Redundant.

2023-08-28 06:23 UTC, HyperBE32 commented on HedgeModManager/Resources/Codesv2/SonicFrontiers.hmm
> +Patch "Disable Drift Dash Panels" in "Gameplay" by "Hyper" does "Disables all Drift Dash Panels seen in 3-5."
Change to "Disables the drift dash panels seen in Cyber Space 3-5."

2023-08-28 06:23 UTC, HyperBE32 commented on HedgeModManager/Resources/Codesv2/SonicFrontiers.hmm
> +Patch "Centre Game Window on Launch" in "System" by "Hyper" does "Centres the game window on launch."
Redundant.

2023-08-28 06:23 UTC, HyperBE32 commented on HedgeModManager/Resources/Codesv2/SonicFrontiers.hmm
> +Patch "Disable Cyloop Aura" in "Graphics" by "Hyper" does "Disables the blue aura that surrounds Sonic while performing a Cyloop."
Change to "Disables the aura around Sonic whilst using Cyloop."

2023-08-28 06:23 UTC, HyperBE32 commented on HedgeModManager/Resources/Codesv2/SonicFrontiers.hmm
> +Patch "Always Sunset on Islands" in "Time" by "NM" does "Forces the time to sunset."
Redundant.

2023-08-28 06:23 UTC, HyperBE32 commented on HedgeModManager/Resources/Codesv2/SonicFrontiers.hmm
> +Patch "Always Sunrise on Islands" in "Time" by "NM" does "Forces the time to sunrise."
Redundant.

2023-08-28 06:23 UTC, HyperBE32 commented on HedgeModManager/Resources/Codesv2/SonicFrontiers.hmm
> +Patch "Always Night on Islands" in "Time" by "NM" does "Forces the time to night."
Redundant.

2023-08-28 06:23 UTC, HyperBE32 commented on HedgeModManager/Resources/Codesv2/SonicFrontiers.hmm
> +Patch "Always Unlocked Spin Dash" in "Cheats" by "Hyper" does "Unlocks Spin Dash at all times."
Redundant.

2023-08-28 06:23 UTC, HyperBE32 commented on HedgeModManager/Resources/Codesv2/SonicFrontiers.hmm
> +Patch "Always Unlocked Extreme Difficulty" in "Cheats" by "Hyper" does "Unlocks Extreme Mode at all times."
Redundant.

2023-08-28 06:23 UTC, HyperBE32 commented on HedgeModManager/Resources/Codesv2/SonicFrontiers.hmm
> +Patch "Always Unlocked Arcade Mode" in "Cheats" by "Hyper" does "Unlocks Arcade Mode at all times."
Redundant.

2023-08-28 06:23 UTC, HyperBE32 commented on HedgeModManager/Resources/Codesv2/SonicFrontiers.hmm
> +Patch "Always Unlocked All Juke Box Songs" in "Cheats" by "Hyper" does "Unlocks all Juke Box songs at all times."
Redundant.

2023-08-28 06:23 UTC, HyperBE32 commented on HedgeModManager/Resources/Codesv2/SonicFrontiers.hmm
> +Patch "Always Trickable Springs" in "Gameplay" by "Hyper" does "Allows Sonic to always trick after using a Spring."
Change "Spring" to lower-case.

2023-08-28 06:23 UTC, HyperBE32 commented on HedgeModManager/Resources/Codesv2/SonicFrontiers.hmm
> +Patch "Always Trickable Jump Boards" in "Gameplay" by "Hyper" does "Allows Sonic to always trick after using a Jump Board."
Change "Jump Board" to lower-case.

2023-08-28 06:23 UTC, HyperBE32 commented on HedgeModManager/Resources/Codesv2/SonicFrontiers.hmm
> +Patch "Always Trickable Dash Rings" in "Gameplay" by "Hyper" does "Allows Sonic to always trick after using a Dash Ring."
Change "Dash Ring" to lower-case.

2023-08-28 06:23 UTC, HyperBE32 commented on HedgeModManager/Resources/Codesv2/SonicFrontiers.hmm
> +Patch "Always Play 'Vandalize' During Credits" in "Audio" by "M&M" does "Plays 'Vandalize' in place of 'One Way Dream' during the credits in Hard mode."
- Change "in place of" to "instead of".
- Change "in Hard mode" to "on Hard difficulty".

2023-08-28 06:23 UTC, HyperBE32 commented on HedgeModManager/Resources/Codesv2/SonicFrontiers.hmm
> +Patch "Always Play 'One Way Dream' During Credits" in "Audio" by "M&M" does "Plays 'One Way Dream' in place of 'Vandalize' during the credits in Normal and Easy modes."
- Change "in place of" to "instead of".
- Change "in Normal and Easy modes" to "on Easy or Normal difficulty".

2023-08-28 06:23 UTC, HyperBE32 commented on HedgeModManager/Resources/Codesv2/SonicFrontiers.hmm
> +Patch "Always Have Power Boost in Cyber Space" in "Cheats" by "Hyper" does "Power Boost is active at all times in Cyber Space."
Redundant.

2023-08-28 06:23 UTC, HyperBE32 commented on HedgeModManager/Resources/Codesv2/SonicFrontiers.hmm
> +Patch "Always Have Power Boost on Islands" in "Cheats" by "SuperSonic16" does "Power Boost is active at all times on the islands."
Redundant.

2023-08-28 06:23 UTC, HyperBE32 commented on HedgeModManager/Resources/Codesv2/SonicFrontiers.hmm
> +Patch "Always Have Phantom Rush" in "Cheats" by "NM" does "Phantom Rush is active at all times."
Redundant.

2023-08-28 06:23 UTC, HyperBE32 commented on HedgeModManager/Resources/Codesv2/SonicFrontiers.hmm
> +Patch "Always Day on Islands" in "Time" by "NM" does "Forces the time to day."
Redundant.

2023-08-28 06:23 UTC, HyperBE32 commented on HedgeModManager/Resources/Codesv2/SonicFrontiers.hmm
> +Code "Allow Attacking from Stomp Bounce" in "Gameplay" by "Hyper" does "Allows Sonic to attack directly after a Stomp Bounce."
Change to "Allows Sonic to perform other actions after performing a stomp bounce."

2023-08-30 19:22 UTC, ActualMandM commented
More than half of these are redundant description additions. Closing.

2023-08-30 19:22 UTC, closed without merging